package com.jeremy.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.id
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.last_name
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.gender
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.email
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.d_id
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.id
     *
     * @return the value of tb_employee.id
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.id
     *
     * @param id the value for tb_employee.id
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.last_name
     *
     * @return the value of tb_employee.last_name
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.last_name
     *
     * @param lastName the value for tb_employee.last_name
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.gender
     *
     * @return the value of tb_employee.gender
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.gender
     *
     * @param gender the value for tb_employee.gender
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.email
     *
     * @return the value of tb_employee.email
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.email
     *
     * @param email the value for tb_employee.email
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.d_id
     *
     * @return the value of tb_employee.d_id
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.d_id
     *
     * @param dId the value for tb_employee.d_id
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}