package com.jeremy.dao;

import com.jeremy.bean.Department;
import java.util.List;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    int updateByPrimaryKey(Department record);
}