package com.jeremy.dao;

import com.jeremy.bean.Employee;
import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Sun Apr 18 16:43:32 BST 2021
     */
    int updateByPrimaryKey(Employee record);
}